//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.24 at 04:31:10 PM EET 
//


package net.sf.mlmechtrade.tafunc.api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sf.mlmechtrade.tafunc.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sf.mlmechtrade.tafunc.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FinancialFunctionType.OutputArguments.OutputArgument }
     * 
     */
    public FinancialFunctionType.OutputArguments.OutputArgument createFinancialFunctionTypeOutputArgumentsOutputArgument() {
        return new FinancialFunctionType.OutputArguments.OutputArgument();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.RequiredInputArguments }
     * 
     */
    public FinancialFunctionType.RequiredInputArguments createFinancialFunctionTypeRequiredInputArguments() {
        return new FinancialFunctionType.RequiredInputArguments();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.RequiredInputArguments.RequiredInputArgument }
     * 
     */
    public FinancialFunctionType.RequiredInputArguments.RequiredInputArgument createFinancialFunctionTypeRequiredInputArgumentsRequiredInputArgument() {
        return new FinancialFunctionType.RequiredInputArguments.RequiredInputArgument();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.Flags }
     * 
     */
    public FinancialFunctionType.Flags createFinancialFunctionTypeFlags() {
        return new FinancialFunctionType.Flags();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.OptionalInputArguments }
     * 
     */
    public FinancialFunctionType.OptionalInputArguments createFinancialFunctionTypeOptionalInputArguments() {
        return new FinancialFunctionType.OptionalInputArguments();
    }

    /**
     * Create an instance of {@link FinancialFunctions }
     * 
     */
    public FinancialFunctions createFinancialFunctions() {
        return new FinancialFunctions();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.OutputArguments.OutputArgument.Flags }
     * 
     */
    public FinancialFunctionType.OutputArguments.OutputArgument.Flags createFinancialFunctionTypeOutputArgumentsOutputArgumentFlags() {
        return new FinancialFunctionType.OutputArguments.OutputArgument.Flags();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.OptionalInputArguments.OptionalInputArgument }
     * 
     */
    public FinancialFunctionType.OptionalInputArguments.OptionalInputArgument createFinancialFunctionTypeOptionalInputArgumentsOptionalInputArgument() {
        return new FinancialFunctionType.OptionalInputArguments.OptionalInputArgument();
    }

    /**
     * Create an instance of {@link FinancialFunctionType }
     * 
     */
    public FinancialFunctionType createFinancialFunctionType() {
        return new FinancialFunctionType();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range }
     * 
     */
    public FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range createFinancialFunctionTypeOptionalInputArgumentsOptionalInputArgumentRange() {
        return new FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range();
    }

    /**
     * Create an instance of {@link FinancialFunctionType.OutputArguments }
     * 
     */
    public FinancialFunctionType.OutputArguments createFinancialFunctionTypeOutputArguments() {
        return new FinancialFunctionType.OutputArguments();
    }

}
