//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.24 at 04:31:10 PM EET 
//


package net.sf.mlmechtrade.tafunc.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinancialFunctionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinancialFunctionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Abbreviation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CamelCaseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupId" type="{}GroupId"/>
 *         &lt;element name="Flags" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Flag" type="{}FunctionFlags" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RequiredInputArguments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RequiredInputArgument" maxOccurs="6">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" type="{}RequiredInputType"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OptionalInputArguments" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OptionalInputArgument" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ShortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LongDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Type" type="{}OptionalInputType"/>
 *                             &lt;element name="Range" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Minimum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Maximum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="SuggestedStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SuggestedEnd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SuggestedIncrement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OutputArguments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OutputArgument" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" type="{}OutputType"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Flags">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Flag" type="{}OutputFlags" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinancialFunctionType", propOrder = {
    "abbreviation",
    "camelCaseName",
    "shortDescription",
    "groupId",
    "flags",
    "requiredInputArguments",
    "optionalInputArguments",
    "outputArguments"
})
public class FinancialFunctionType {

    @XmlElement(name = "Abbreviation", required = true)
    protected String abbreviation;
    @XmlElement(name = "CamelCaseName", required = true)
    protected String camelCaseName;
    @XmlElement(name = "ShortDescription", required = true)
    protected String shortDescription;
    @XmlElement(name = "GroupId", required = true)
    protected GroupId groupId;
    @XmlElement(name = "Flags")
    protected FinancialFunctionType.Flags flags;
    @XmlElement(name = "RequiredInputArguments", required = true)
    protected FinancialFunctionType.RequiredInputArguments requiredInputArguments;
    @XmlElement(name = "OptionalInputArguments")
    protected FinancialFunctionType.OptionalInputArguments optionalInputArguments;
    @XmlElement(name = "OutputArguments", required = true)
    protected FinancialFunctionType.OutputArguments outputArguments;

    /**
     * Gets the value of the abbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * Sets the value of the abbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbreviation(String value) {
        this.abbreviation = value;
    }

    /**
     * Gets the value of the camelCaseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCamelCaseName() {
        return camelCaseName;
    }

    /**
     * Sets the value of the camelCaseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCamelCaseName(String value) {
        this.camelCaseName = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link GroupId }
     *     
     */
    public GroupId getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupId }
     *     
     */
    public void setGroupId(GroupId value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialFunctionType.Flags }
     *     
     */
    public FinancialFunctionType.Flags getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialFunctionType.Flags }
     *     
     */
    public void setFlags(FinancialFunctionType.Flags value) {
        this.flags = value;
    }

    /**
     * Gets the value of the requiredInputArguments property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialFunctionType.RequiredInputArguments }
     *     
     */
    public FinancialFunctionType.RequiredInputArguments getRequiredInputArguments() {
        return requiredInputArguments;
    }

    /**
     * Sets the value of the requiredInputArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialFunctionType.RequiredInputArguments }
     *     
     */
    public void setRequiredInputArguments(FinancialFunctionType.RequiredInputArguments value) {
        this.requiredInputArguments = value;
    }

    /**
     * Gets the value of the optionalInputArguments property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialFunctionType.OptionalInputArguments }
     *     
     */
    public FinancialFunctionType.OptionalInputArguments getOptionalInputArguments() {
        return optionalInputArguments;
    }

    /**
     * Sets the value of the optionalInputArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialFunctionType.OptionalInputArguments }
     *     
     */
    public void setOptionalInputArguments(FinancialFunctionType.OptionalInputArguments value) {
        this.optionalInputArguments = value;
    }

    /**
     * Gets the value of the outputArguments property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialFunctionType.OutputArguments }
     *     
     */
    public FinancialFunctionType.OutputArguments getOutputArguments() {
        return outputArguments;
    }

    /**
     * Sets the value of the outputArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialFunctionType.OutputArguments }
     *     
     */
    public void setOutputArguments(FinancialFunctionType.OutputArguments value) {
        this.outputArguments = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Flag" type="{}FunctionFlags" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flag"
    })
    public static class Flags {

        @XmlElement(name = "Flag", required = true)
        protected List<FunctionFlags> flag;

        /**
         * Gets the value of the flag property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flag property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlag().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FunctionFlags }
         * 
         * 
         */
        public List<FunctionFlags> getFlag() {
            if (flag == null) {
                flag = new ArrayList<FunctionFlags>();
            }
            return this.flag;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OptionalInputArgument" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ShortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LongDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Type" type="{}OptionalInputType"/>
     *                   &lt;element name="Range" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Minimum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Maximum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="SuggestedStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SuggestedEnd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SuggestedIncrement" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "optionalInputArgument"
    })
    public static class OptionalInputArguments {

        @XmlElement(name = "OptionalInputArgument", required = true)
        protected List<FinancialFunctionType.OptionalInputArguments.OptionalInputArgument> optionalInputArgument;

        /**
         * Gets the value of the optionalInputArgument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the optionalInputArgument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOptionalInputArgument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FinancialFunctionType.OptionalInputArguments.OptionalInputArgument }
         * 
         * 
         */
        public List<FinancialFunctionType.OptionalInputArguments.OptionalInputArgument> getOptionalInputArgument() {
            if (optionalInputArgument == null) {
                optionalInputArgument = new ArrayList<FinancialFunctionType.OptionalInputArguments.OptionalInputArgument>();
            }
            return this.optionalInputArgument;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ShortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LongDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Type" type="{}OptionalInputType"/>
         *         &lt;element name="Range" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Minimum" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Maximum" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="SuggestedStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SuggestedEnd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SuggestedIncrement" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "shortDescription",
            "longDescription",
            "type",
            "range",
            "defaultValue",
            "camelCaseName",
            "cType",
            "cMexType"
        })
        public static class OptionalInputArgument {

            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "ShortDescription", required = true)
            protected String shortDescription;
            @XmlElement(name = "LongDescription")
            protected String longDescription;
            @XmlElement(name = "Type", required = true)
            protected OptionalInputType type;
            @XmlElement(name = "Range")
            protected FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range range;
            @XmlElement(name = "DefaultValue")
            protected String defaultValue;
            @XmlElement(name = "SuggestedIncrement", required = false)
            protected String camelCaseName;
            @XmlElement(name = "cType", required = false)
            protected String cType;
            @XmlElement(name = "cMexType", required = false)
            protected String cMexType;


            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the shortDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShortDescription() {
                return shortDescription;
            }

            /**
             * Sets the value of the shortDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShortDescription(String value) {
                this.shortDescription = value;
            }

            /**
             * Gets the value of the longDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLongDescription() {
                return longDescription;
            }

            /**
             * Sets the value of the longDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLongDescription(String value) {
                this.longDescription = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link OptionalInputType }
             *     
             */
            public OptionalInputType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link OptionalInputType }
             *     
             */
            public void setType(OptionalInputType value) {
                this.type = value;
            }

            /**
             * Gets the value of the range property.
             * 
             * @return
             *     possible object is
             *     {@link FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range }
             *     
             */
            public FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range getRange() {
                return range;
            }

            /**
             * Sets the value of the range property.
             * 
             * @param value
             *     allowed object is
             *     {@link FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range }
             *     
             */
            public void setRange(FinancialFunctionType.OptionalInputArguments.OptionalInputArgument.Range value) {
                this.range = value;
            }

            /**
             * Gets the value of the defaultValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDefaultValue() {
                return defaultValue;
            }

            /**
             * Sets the value of the defaultValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDefaultValue(String value) {
                this.defaultValue = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Minimum" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Maximum" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="SuggestedStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SuggestedEnd" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SuggestedIncrement" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "minimum",
                "maximum",
                "precision",
                "suggestedStart",
                "suggestedEnd",
                "suggestedIncrement"
            })
            public static class Range {

                @XmlElement(name = "Minimum", required = true)
                protected String minimum;
                @XmlElement(name = "Maximum", required = true)
                protected String maximum;
                @XmlElement(name = "Precision")
                protected String precision;
                @XmlElement(name = "SuggestedStart", required = true)
                protected String suggestedStart;
                @XmlElement(name = "SuggestedEnd", required = true)
                protected String suggestedEnd;
                @XmlElement(name = "SuggestedIncrement", required = true)
                protected String suggestedIncrement;

                /**
                 * Gets the value of the minimum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinimum() {
                    return minimum;
                }

                /**
                 * Sets the value of the minimum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinimum(String value) {
                    this.minimum = value;
                }

                /**
                 * Gets the value of the maximum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMaximum() {
                    return maximum;
                }

                /**
                 * Sets the value of the maximum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMaximum(String value) {
                    this.maximum = value;
                }

                /**
                 * Gets the value of the precision property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPrecision() {
                    return precision;
                }

                /**
                 * Sets the value of the precision property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPrecision(String value) {
                    this.precision = value;
                }

                /**
                 * Gets the value of the suggestedStart property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuggestedStart() {
                    return suggestedStart;
                }

                /**
                 * Sets the value of the suggestedStart property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuggestedStart(String value) {
                    this.suggestedStart = value;
                }

                /**
                 * Gets the value of the suggestedEnd property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuggestedEnd() {
                    return suggestedEnd;
                }

                /**
                 * Sets the value of the suggestedEnd property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuggestedEnd(String value) {
                    this.suggestedEnd = value;
                }

                /**
                 * Gets the value of the suggestedIncrement property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuggestedIncrement() {
                    return suggestedIncrement;
                }

                /**
                 * Sets the value of the suggestedIncrement property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuggestedIncrement(String value) {
                    this.suggestedIncrement = value;
                }

            }


			public String getCamelCaseName() {
				return camelCaseName;
			}

			public void setCamelCaseName(String camelCaseName) {
				this.camelCaseName = camelCaseName;
			}

			public String getCType() {
				return cType;
			}

			public void setCType(String type) {
				cType = type;
			}

			public String getCMexType() {
				return cMexType;
			}

			public void setCMexType(String mexType) {
				cMexType = mexType;
			}

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OutputArgument" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Type" type="{}OutputType"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Flags">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Flag" type="{}OutputFlags" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "outputArgument"
    })
    public static class OutputArguments {

        @XmlElement(name = "OutputArgument", required = true)
        protected List<FinancialFunctionType.OutputArguments.OutputArgument> outputArgument;

        /**
         * Gets the value of the outputArgument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the outputArgument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOutputArgument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FinancialFunctionType.OutputArguments.OutputArgument }
         * 
         * 
         */
        public List<FinancialFunctionType.OutputArguments.OutputArgument> getOutputArgument() {
            if (outputArgument == null) {
                outputArgument = new ArrayList<FinancialFunctionType.OutputArguments.OutputArgument>();
            }
            return this.outputArgument;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Type" type="{}OutputType"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Flags">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Flag" type="{}OutputFlags" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "name",
            "flags",
            "cType",
            "camelCaseName",
            "notLast"
        })
        public static class OutputArgument {

            @XmlElement(name = "Type", required = true)
            protected OutputType type;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Flags", required = true)
            protected FinancialFunctionType.OutputArguments.OutputArgument.Flags flags;
            @XmlElement(name = "cType", required = false)
            protected String cType;
            @XmlElement(name = "camelCaseName", required = false)            
            protected String camelCaseName;
            @XmlElement(name = "notLast", required = false)
            protected boolean notLast;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link OutputType }
             *     
             */
            public OutputType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link OutputType }
             *     
             */
            public void setType(OutputType value) {
                this.type = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the flags property.
             * 
             * @return
             *     possible object is
             *     {@link FinancialFunctionType.OutputArguments.OutputArgument.Flags }
             *     
             */
            public FinancialFunctionType.OutputArguments.OutputArgument.Flags getFlags() {
                return flags;
            }

            /**
             * Sets the value of the flags property.
             * 
             * @param value
             *     allowed object is
             *     {@link FinancialFunctionType.OutputArguments.OutputArgument.Flags }
             *     
             */
            public void setFlags(FinancialFunctionType.OutputArguments.OutputArgument.Flags value) {
                this.flags = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Flag" type="{}OutputFlags" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "flag"
            })
            public static class Flags {

                @XmlElement(name = "Flag", required = true)
                protected List<OutputFlags> flag;

                /**
                 * Gets the value of the flag property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the flag property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFlag().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link OutputFlags }
                 * 
                 * 
                 */
                public List<OutputFlags> getFlag() {
                    if (flag == null) {
                        flag = new ArrayList<OutputFlags>();
                    }
                    return this.flag;
                }

            }


			public String getCType() {
				return cType;
			}

			public void setCType(String type) {
				cType = type;
			}

			public String getCamelCaseName() {
				return camelCaseName;
			}

			public void setCamelCaseName(String camelCaseName) {
				this.camelCaseName = camelCaseName;
			}

			public boolean isNotLast() {
				return notLast;
			}

			public void setNotLast(boolean notLast) {
				this.notLast = notLast;
			}

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RequiredInputArgument" maxOccurs="6">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Type" type="{}RequiredInputType"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requiredInputArgument"
    })
    public static class RequiredInputArguments {

        @XmlElement(name = "RequiredInputArgument", required = true)
        protected List<FinancialFunctionType.RequiredInputArguments.RequiredInputArgument> requiredInputArgument;

        /**
         * Gets the value of the requiredInputArgument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requiredInputArgument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequiredInputArgument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FinancialFunctionType.RequiredInputArguments.RequiredInputArgument }
         * 
         * 
         */
        public List<FinancialFunctionType.RequiredInputArguments.RequiredInputArgument> getRequiredInputArgument() {
            if (requiredInputArgument == null) {
                requiredInputArgument = new ArrayList<FinancialFunctionType.RequiredInputArguments.RequiredInputArgument>();
            }
            return this.requiredInputArgument;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Type" type="{}RequiredInputType"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "name",
            "cType",
            "camelCaseName",
            "cMexType"
        })
        public static class RequiredInputArgument {

            @XmlElement(name = "Type", required = true)
            protected RequiredInputType type;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "cType", required = false)
            protected String cType;
            @XmlElement(name = "camelCaseName", required = false)
            protected String camelCaseName;
            @XmlElement(name = "cMexType", required = false)
            protected String  cMexType;
            

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link RequiredInputType }
             *     
             */
            public RequiredInputType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link RequiredInputType }
             *     
             */
            public void setType(RequiredInputType value) {
                this.type = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

			public String getCType() {
				return cType;
			}

			public void setCType(String type) {
				cType = type;
			}

			public String getCamelCaseName() {
				return camelCaseName;
			}

			public void setCamelCaseName(String camelCaseName) {
				this.camelCaseName = camelCaseName;
			}

			public String getCMexType() {
				return cMexType;
			}

			public void setCMexType(String mexType) {
				cMexType = mexType;
			}

        }

    }

}
