//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.24 at 04:31:10 PM EET 
//


package net.sf.mlmechtrade.tafunc.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctionFlags.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FunctionFlags">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Overlap"/>
 *     &lt;enumeration value="Volume"/>
 *     &lt;enumeration value="Candlestick"/>
 *     &lt;enumeration value="Unstable Period"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FunctionFlags")
@XmlEnum
public enum FunctionFlags {

    @XmlEnumValue("Overlap")
    OVERLAP("Overlap"),
    @XmlEnumValue("Volume")
    VOLUME("Volume"),
    @XmlEnumValue("Candlestick")
    CANDLESTICK("Candlestick"),
    @XmlEnumValue("Unstable Period")
    UNSTABLE_PERIOD("Unstable Period");
    private final String value;

    FunctionFlags(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FunctionFlags fromValue(String v) {
        for (FunctionFlags c: FunctionFlags.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
