//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.24 at 04:31:10 PM EET 
//


package net.sf.mlmechtrade.tafunc.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupId.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GroupId">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Math Operators"/>
 *     &lt;enumeration value="Math Transform"/>
 *     &lt;enumeration value="Overlap Studies"/>
 *     &lt;enumeration value="Volatility Indicators"/>
 *     &lt;enumeration value="Momentum Indicators"/>
 *     &lt;enumeration value="Cycle Indicators"/>
 *     &lt;enumeration value="Volume Indicators"/>
 *     &lt;enumeration value="Pattern Recognition"/>
 *     &lt;enumeration value="Statistic Functions"/>
 *     &lt;enumeration value="Price Transform"/>
 *     &lt;enumeration value="Undefined"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GroupId")
@XmlEnum
public enum GroupId {

    @XmlEnumValue("Math Operators")
    MATH_OPERATORS("Math Operators"),
    @XmlEnumValue("Math Transform")
    MATH_TRANSFORM("Math Transform"),
    @XmlEnumValue("Overlap Studies")
    OVERLAP_STUDIES("Overlap Studies"),
    @XmlEnumValue("Volatility Indicators")
    VOLATILITY_INDICATORS("Volatility Indicators"),
    @XmlEnumValue("Momentum Indicators")
    MOMENTUM_INDICATORS("Momentum Indicators"),
    @XmlEnumValue("Cycle Indicators")
    CYCLE_INDICATORS("Cycle Indicators"),
    @XmlEnumValue("Volume Indicators")
    VOLUME_INDICATORS("Volume Indicators"),
    @XmlEnumValue("Pattern Recognition")
    PATTERN_RECOGNITION("Pattern Recognition"),
    @XmlEnumValue("Statistic Functions")
    STATISTIC_FUNCTIONS("Statistic Functions"),
    @XmlEnumValue("Price Transform")
    PRICE_TRANSFORM("Price Transform"),
    @XmlEnumValue("Undefined")
    UNDEFINED("Undefined");
    private final String value;

    GroupId(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GroupId fromValue(String v) {
        for (GroupId c: GroupId.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
