//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.24 at 04:31:10 PM EET 
//


package net.sf.mlmechtrade.tafunc.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequiredInputType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequiredInputType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Open"/>
 *     &lt;enumeration value="High"/>
 *     &lt;enumeration value="Low"/>
 *     &lt;enumeration value="Close"/>
 *     &lt;enumeration value="Volume"/>
 *     &lt;enumeration value="Open Interest"/>
 *     &lt;enumeration value="Double Array"/>
 *     &lt;enumeration value="Integer Array"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RequiredInputType")
@XmlEnum
public enum RequiredInputType {

    @XmlEnumValue("Open")
    OPEN("Open"),
    @XmlEnumValue("High")
    HIGH("High"),
    @XmlEnumValue("Low")
    LOW("Low"),
    @XmlEnumValue("Close")
    CLOSE("Close"),
    @XmlEnumValue("Volume")
    VOLUME("Volume"),
    @XmlEnumValue("Open Interest")
    OPEN_INTEREST("Open Interest"),
    @XmlEnumValue("Double Array")
    DOUBLE_ARRAY("Double Array"),
    @XmlEnumValue("Integer Array")
    INTEGER_ARRAY("Integer Array");
    private final String value;

    private String cType;
    
    RequiredInputType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequiredInputType fromValue(String v) {
        for (RequiredInputType c: RequiredInputType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

	public String getCType() {
		return cType;
	}

	public void setCType(String type) {
		cType = type;
	}

}
